name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: 'src\KeePassCPEO.sln'
  BUILD_CONFIGURATION: Release
  TEST_PROJECT_PATH: 'src\KeePassCPEO.Tests\KeePassCPEO.Tests.csproj'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4.1.1

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Solution
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:RestorePackages=false

    - name: Run Unit Tests
      run: dotnet test ${{env.TEST_PROJECT_PATH}} -c ${{env.BUILD_CONFIGURATION}} --no-build